<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>
  <parent>
    <groupId>com.serverpanel</groupId>
    <artifactId>serverpanel-backend</artifactId>
    <version>1.0.0</version>
  </parent>

  <artifactId>server-system</artifactId>
  <name>ServerPanel :: System</name>
  <description>系统管理：用户/角色/菜单/字典/参数配置/审计日志/登录日志/认证</description>

  <dependencies>
    <dependency>
      <groupId>com.serverpanel</groupId>
      <artifactId>server-framework</artifactId>
    </dependency>
    <!-- IP 归属地离线查询（工作台-访问来源） -->
    <dependency>
      <groupId>org.lionsoul</groupId>
      <artifactId>ip2region</artifactId>
    </dependency>
  </dependencies>
</project>
