# Generated by ServerPanel - stream ${name}
# Managed file, do not edit manually.
server {
    listen ${port}${listenSuffix};
    proxy_pass ${upstreamHost}:${upstreamPort};
    proxy_connect_timeout ${proxyTimeout}s;
    proxy_timeout ${proxyTimeout}s;
}
