# Generated by ServerPanel - ${siteName}
# Managed file, do not edit manually.
<#macro proxyBody>
${locationsBlock}    location / {
        proxy_pass ${upstream};
        proxy_http_version 1.1;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
</#macro>
<#if sslEnabled>
server {
    listen 80;
    listen [::]:80;
    server_name ${serverNames};
<#if httpRedirect>
    return 301 https://${primaryDomain}$request_uri;
<#else>
<@proxyBody/>
</#if>
}

server {
    listen 443 ssl;
    listen [::]:443 ssl;
    http2 on;
    ssl_certificate     ${certPath};
    ssl_certificate_key ${keyPath};
    ssl_protocols       TLSv1.2 TLSv1.3;
    ssl_ciphers         HIGH:!aNULL:!MD5;
    ssl_prefer_server_ciphers on;
<#if hsts>
    add_header Strict-Transport-Security "max-age=31536000" always;
</#if>
    server_name ${serverNames};

    access_log ${logDir}/${name}.access.log;
    error_log  ${logDir}/${name}.error.log;

<@proxyBody/>
}
<#else>
server {
    listen 80;
    listen [::]:80;
    server_name ${serverNames};

    access_log ${logDir}/${name}.access.log;
    error_log  ${logDir}/${name}.error.log;

<@proxyBody/>
}
</#if>
