# Generated by ServerPanel - upstream ${name}
# Managed file, do not edit manually.
upstream ${name} {
<#if strategyDirective != "">    ${strategyDirective}
</#if><#list servers as s>    server ${s};
</#list><#if keepalive gt 0>    keepalive ${keepalive};
</#if>}
