# Generated by ServerPanel - ${siteName}
# Managed file, do not edit manually.
<#macro staticBody>
${locationsBlock}    location / {
        root  ${staticRoot};
        index index.html index.htm;
        try_files $uri $uri/ =404;
    }
</#macro>
<#if sslEnabled>
server {
    listen 80;
    listen [::]:80;
    server_name ${serverNames};
<#if httpRedirect>
    return 301 https://${primaryDomain}$request_uri;
<#else>
<@staticBody/>
</#if>
}

server {
    listen 443 ssl;
    listen [::]:443 ssl;
    http2 on;
    ssl_certificate     ${certPath};
    ssl_certificate_key ${keyPath};
    ssl_protocols       TLSv1.2 TLSv1.3;
    ssl_ciphers         HIGH:!aNULL:!MD5;
    ssl_prefer_server_ciphers on;
<#if hsts>
    add_header Strict-Transport-Security "max-age=31536000" always;
</#if>
    server_name ${serverNames};

    access_log ${logDir}/${name}.access.log;
    error_log  ${logDir}/${name}.error.log;

<@staticBody/>
}
<#else>
server {
    listen 80;
    listen [::]:80;
    server_name ${serverNames};

    access_log ${logDir}/${name}.access.log;
    error_log  ${logDir}/${name}.error.log;

<@staticBody/>
}
</#if>
