# Generated by ServerPanel - ${siteName}
# Managed file, do not edit manually.
<#if sslEnabled>
server {
    listen 80;
    listen [::]:80;
    server_name ${domain};
    return 301 https://${domain}$request_uri;
}

</#if>
server {
<#if sslEnabled>
    listen 443 ssl;
    listen [::]:443 ssl;
    http2 on;
    ssl_certificate     ${certPath};
    ssl_certificate_key ${keyPath};
    ssl_protocols       TLSv1.2 TLSv1.3;
    ssl_ciphers         HIGH:!aNULL:!MD5;
    ssl_prefer_server_ciphers on;
<#else>
    listen 80;
    listen [::]:80;
</#if>
    server_name ${domain};

    access_log /var/log/nginx/${domain}.access.log;
    error_log  /var/log/nginx/${domain}.error.log;

    root  ${staticRoot};
    index index.html index.htm;

    location / {
        try_files $uri $uri/ =404;
    }
}
